# 应用
app:
  name: gin
  mode: debug # debug|test|release debug=本地环境 test=测试环境 release=生产环境
  port: 8080
  timezone: Asia/Shanghai
  proxies: 127.0.0.1/8080,127.0.0.1:8081 # 代理地址多个地址用逗号分隔
  env: dev # dev|testing|production dev=本地环境 testing=测试环境 production=生产环境
# Mysql数据库
mysql:
  # host: "username:password@tcp(127.0.0.1:3306)/databaseName?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  database: gin
  # 慢查询的时间(ms) 超过这个时间会记录到日志中
  slow-query-seconds: 3s
# 缓存
cache:
  driver: "memory"  # memory|disk|redis # 为空默认内存缓存
  # Redis数据库
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0
# 跨域
cors:
  enabled: true # 是否开启跨域
  allow-origin: "*" # 允许访问的域名列表
  allow-headers: "*" # 允许的请求头列表
  expose-headers: "*" # 允许返回的响应头列表
  allow-methods: GET, POST, PUT, DELETE, OPTIONS # 允许的请求方法列表
  allow-credentials: "true" # 是否允许发送cookie
# Jwt
jwt:
  key: 123456789!@# # 加解密秘钥key
  exp: 7200 # 过期时间(单位秒) 2*60*60
  refresh-exp: 172800  # 刷新过期时间(单位秒) 2*24*60*60
